### ISSUE TITLE
关于yolo8模型部署

### ISSUE THREAD

**Issue by suyuan945** [wkt/YoloMobile#4]
我尝试官方的输出ncnn模型做部署，尝试解析结果。但发现输出好像是有些问题。请问下输入在做了归一化，通道变换还有别的吗，对于输出纬度为84*8400，将数据变为8400*84，然后遍历选择符合阈值的结果，最终采用NMS输出结果。上述是我做的步骤

**Comment by wkt** [comment]
目前仅支持，如下代码生成的ncnn模型：
```
from ultralytics import YOLO

# Load a model
model = YOLO('path/to/best.pt')  # load a custom trained model

# Export the model
model.export(format='ncnn', imgsz=640)
```
并input_size=imgsz。
至于处理/解析模型的直接输出，可参考：YoloMobile/src/main/cpp/Yolo.cpp

**Comment by suyuan945** [comment]
感谢回复信息，我试一下。

**Comment by ice6** [comment]
yolov8的格式转换存在一些问题，用它的命令行可以正确转换，用代码方式就不行了。（贴在这里方便后面看到这个帖子的人）

`yolo export format=ncnn model=runs/detect/train/weights/best.pt imgsz=640`

Ultralytics YOLOv8.2.98 🚀 Python-3.10.14 torch-2.4.1 CPU (13th Gen Intel Core(TM) i9-13900HX)
YOLOv8x summary (fused): 268 layers, 68,145,717 parameters, 0 gradients, 257.5 GFLOPs

PyTorch: starting from 'runs/detect/train/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 27, 8400) (130.4 MB)

TorchScript: starting export with torch 2.4.1...
TorchScript: export success ✅ 3.4s, saved as 'runs/detect/train/weights/best.torchscript' (260.5 MB)

NCNN: starting export with NCNN 1.0.20240820...
NCNN: WARNING ⚠️ PNNX not found. Attempting to download binary file from https://github.com/pnnx/pnnx/.
Note PNNX Binary file must be placed in current working directory or in /root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics. See PNNX repo for full installation instructions.
NCNN: successfully found latest PNNX asset file pnnx-20240819-linux.zip
Downloading https://github.com/pnnx/pnnx/releases/download/20240819/pnnx-20240819-linux.zip to 'pnnx-20240819-linux.zip'...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 21.4M/21.4M [00:03<00:00, 6.15MB/s]
Unzipping pnnx-20240819-linux.zip to /root/dataset/dnj/5nc23/pnnx-20240819-linux...: 100%|██████████| 3/3 [00:00<00:00, 12.27file/s]
NCNN: running '/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/pnnx runs/detect/train/weights/best.torchscript ncnnparam=runs/detect/train/weights/best_ncnn_model/model.ncnn.param ncnnbin=runs/detect/train/weights/best_ncnn_model/model.ncnn.bin ncnnpy=runs/detect/train/weights/best_ncnn_model/model_ncnn.py pnnxparam=runs/detect/train/weights/best_ncnn_model/model.pnnx.param pnnxbin=runs/detect/train/weights/best_ncnn_model/model.pnnx.bin pnnxpy=runs/detect/train/weights/best_ncnn_model/model_pnnx.py pnnxonnx=runs/detect/train/weights/best_ncnn_model/model.pnnx.onnx fp16=0 device=cpu inputshape="[1, 3, 640, 640]"'
pnnxparam = runs/detect/train/weights/best_ncnn_model/model.pnnx.param
pnnxbin = runs/detect/train/weights/best_ncnn_model/model.pnnx.bin
pnnxpy = runs/detect/train/weights/best_ncnn_model/model_pnnx.py
pnnxonnx = runs/detect/train/weights/best_ncnn_model/model.pnnx.onnx
ncnnparam = runs/detect/train/weights/best_ncnn_model/model.ncnn.param
ncnnbin = runs/detect/train/weights/best_ncnn_model/model.ncnn.bin
ncnnpy = runs/detect/train/weights/best_ncnn_model/model_ncnn.py
fp16 = 0
optlevel = 2
device = cpu
inputshape = [1,3,640,640]f32
inputshape2 =
customop =
moduleop =
############# pass_level0
inline module = ultralytics.nn.modules.block.Bottleneck
inline module = ultralytics.nn.modules.block.C2f
inline module = ultralytics.nn.modules.block.DFL
inline module = ultralytics.nn.modules.block.SPPF
inline module = ultralytics.nn.modules.conv.Concat
inline module = ultralytics.nn.modules.conv.Conv
inline module = ultralytics.nn.modules.head.Detect
inline module = ultralytics.nn.modules.block.Bottleneck
inline module = ultralytics.nn.modules.block.C2f
inline module = ultralytics.nn.modules.block.DFL
inline module = ultralytics.nn.modules.block.SPPF
inline module = ultralytics.nn.modules.conv.Concat
inline module = ultralytics.nn.modules.conv.Conv
inline module = ultralytics.nn.modules.head.Detect

----------------

############# pass_level1
############# pass_level2
############# pass_level3
############# pass_level4
############# pass_level5
############# pass_ncnn
NCNN: export success ✅ 18.2s, saved as 'runs/detect/train/weights/best_ncnn_model' (260.1 MB)

Export complete (23.2s)
Results saved to /root/dataset/dnj/5nc23/runs/detect/train/weights
Predict:         yolo predict task=detect model=runs/detect/train/weights/best_ncnn_model imgsz=640
Validate:        yolo val task=detect model=runs/detect/train/weights/best_ncnn_model imgsz=640 data=data.yaml
Visualize:       https://netron.app
💡 Learn more at https://docs.ultralytics.com/modes/export

when I run the code
```
from ultralytics import YOLO

# Load a model
model = YOLO('runs/detect/train/weights/best.pt ')  # load a custom trained model

# Export the model
model.export(format='ncnn', imgsz=640)
```
 `python ncnn.py`
Ultralytics YOLOv8.2.98 🚀 Python-3.10.14 torch-2.4.1 CPU (13th Gen Intel Core(TM) i9-13900HX)
YOLOv8x summary (fused): 268 layers, 68,145,717 parameters, 0 gradients, 257.5 GFLOPs

PyTorch: starting from 'runs/detect/train/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 27, 8400) (130.4 MB)

TorchScript: starting export with torch 2.4.1...
TorchScript: export success ✅ 3.4s, saved as 'runs/detect/train/weights/best.torchscript' (260.5 MB)
Ultralytics YOLOv8.2.98 🚀 Python-3.10.14 torch-2.4.1 CPU (13th Gen Intel Core(TM) i9-13900HX)
YOLOv8x summary (fused): 268 layers, 68,145,717 parameters, 0 gradients, 257.5 GFLOPs

PyTorch: starting from 'runs/detect/train/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 27, 8400) (130.4 MB)

TorchScript: starting export with torch 2.4.1...
TorchScript: export success ✅ 3.3s, saved as 'runs/detect/train/weights/best.torchscript' (260.6 MB)
NCNN: export failure ❌ 0.0s: partially initialized module 'ncnn' has no attribute '__version__' (most likely due to a circular import)
NCNN: export failure ❌ 5.0s: partially initialized module 'ncnn' has no attribute '__version__' (most likely due to a circular import)
Traceback (most recent call last):
  File "/root/dataset/dnj/5nc23/ncnn.py", line 7, in <module>
    model.export(format='ncnn', imgsz=640)
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/engine/model.py", line 735, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 324, in __call__
    f[11], _ = self.export_ncnn()
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 140, in outer_func
    raise e
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 135, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 534, in export_ncnn
    import ncnn  # noqa
  File "/root/dataset/dnj/5nc23/ncnn.py", line 7, in <module>
    model.export(format='ncnn', imgsz=640)
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/engine/model.py", line 735, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 324, in __call__
    f[11], _ = self.export_ncnn()
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 140, in outer_func
    raise e
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 135, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/root/anaconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 536, in export_ncnn
    LOGGER.info(f"\n{prefix} starting export with NCNN {ncnn.__version__}...")
AttributeError: partially initialized module 'ncnn' has no attribute '__version__' (most likely due to a circular import)


post here just for reference.
